import os

from fpdf import FPDF

from os.path import exists

import qrcode_gen

import env

page_width = 210
pdf = FPDF()

pdf.set_font("Helvetica", size=20)

line_height = pdf.font_size * 1.1

dirname = os.path.dirname(__file__)


def pdf_header(title=""):
    # Contact details
    address = "162/1, Panasara Mw, Halloluwa"
    email = "info@thotupolaresidence.lk"
    mobile = "0773389665 / 0777802093"
    tele_phone = "0812492754"
    website = "https://thotupolaresidence.lk"

    # Config

    pdf.add_page()

    # Top Line
    pdf.set_draw_color(255, 159, 53)
    pdf.set_fill_color(255, 159, 53)
    pdf.rect(0, 0, page_width, 0.5, style="FD")

    # Logo
    logo = env.dirname.join("/images/logo.png")
    if exists(logo):
        pdf.image(logo, 10, 10, 40)
    else:
        pdf.multi_cell(1, ln=3)

    # Header
    pdf.set_text_color(0, 55, 129)
    pdf.multi_cell(page_width - 20, 10, title, align="R", ln=1)
    pdf.ln(8)

    # Body style config
    pdf.set_draw_color(220, 220, 220)
    pdf.set_line_width(0.4)
    pdf.set_font_size(10)
    pdf.set_text_color(80, 80, 80)

    pdf.multi_cell(190, line_height / 6, "", ln=1, border="0")
    pdf.multi_cell(28, line_height / 1.6, "Email Address", ln=3, border="0")
    pdf.multi_cell(page_width - 55, line_height / 1.6, f" : {email}", ln=1, border="0")
    pdf.multi_cell(28, line_height / 1.6, "Hotel Tel", ln=3, border="0")
    pdf.multi_cell(page_width - 55, line_height / 1.6, f" : {tele_phone}", ln=1, border="0")
    pdf.multi_cell(28, line_height / 1.6, "Mobile", ln=3, border="0")
    pdf.multi_cell(page_width - 55, line_height / 1.6, f" : {mobile}", ln=1, border="0")
    pdf.multi_cell(28, line_height / 1.6, "Address", ln=3, border="0")
    pdf.multi_cell(page_width - 55, line_height / 1.6, f" : {address}", ln=1, border="0")
    pdf.multi_cell(28, line_height / 1.6, "Website", ln=3, border="0")
    pdf.multi_cell(page_width - 55, line_height / 1.6, f" : {website}", ln=1, border="0", link=website)
    pdf.multi_cell(190, line_height / 6, "", ln=1, border="0")
    # QR
    pdf.image(get_info_qr("details_qr", f"A:{address}, E:{email}, M:{mobile}, T:{tele_phone}, W:{website}"),
              page_width - 38, 26,
              w=28)

    pdf.ln(8)


def pdf_footer():
    pdf.ln(10)

    # Message
    pdf.set_font_size(9)
    line_height = pdf.font_size * 2
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(page_width - 20, line_height / 1.8,
                   "Thank you for being our valued customer. We are so grateful for serving you and hope we met your expectations. Always happy to hear from you.",
                   ln=1)
    pdf.ln(2)

    # Bottom info
    pdf.set_font_size(8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(95, line_height, "Generated by Thotupola Residence", ln=3)
    pdf.multi_cell(95, line_height, "https://thotupolaresidence.lk", link="https://thotupolaresidence.lk", ln=1,
                   align="R")
    pdf.image(f'{env.dirname}/images/7sb.png', 11, w=8, link="https://sevensbay.com")
    pdf.set_font_size(6)
    pdf.multi_cell(50, line_height / 2, "Software")


def get_info_qr(name, info):
    file = f"{env.dirname}/images/{name}.png"
    if not exists(file):
        # Generate QR code for website
        qrcode_gen.generate_qr(file, info)
    return file
